### ISSUE TITLE
Add one accepted CVPR 2021 paper 

### ISSUE THREAD

**Issue by Nicholasli1995** [extreme-assistant/CVPR2021-Paper-Code-Interpretation#52]
Topic: 3D object detection, 3D pose estimation, vehicle pose estimation
Title: Exploring intermediate representation for monocular vehicle pose estimation
Code: https://github.com/Nicholasli1995/EgoNet
@extreme-assistant

**Comment by Nicholasli1995** [comment]
Link: https://arxiv.org/abs/2011.08464

**Comment by extreme-assistant** [comment]
This paper has been added. Thank you for the information.
