### ISSUE TITLE
Add our CVPR paper

### ISSUE THREAD

**Issue by SikaStar** [extreme-assistant/CVPR2021-Paper-Code-Interpretation#57]
Hi, thank you for your collection! Please add our CVPR paper "Generalizable Person Re-identification with Relevance-aware Mixture of Experts". In this paper, we propose a novel method called the relevance-aware mixture of experts (RaMoE) to tackle the problem of domain generalization in person re-identification. Paper link [https://arxiv.org/abs/2105.09156](url).

**Comment by extreme-assistant** [comment]
This paper has been added. Thank you for the information.
